spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: user_service
          uri: lb://USER-SERVICE/
          predicates:
            - Path=/users/**
      discovery:
        locator:
          enabled: true

server:
  port: 4000
